package opcode

var (
	RecvOps recvOpcode
)

type recvOpcode struct {
	// GENERIC
	PONG         int16
	CLIENT_ERROR int16
	STRANGE_DATA int16
	// LOGIN
	LOGIN_PASSWORD        int16
	GUEST_LOGIN           int16 `properties:"GUEST_LOGIN,default=65535"`
	LICENSE_REQUEST       int16
	SERVERLIST_REREQUEST  int16
	CHARLIST_REQUEST      int16
	SERVERSTATUS_REQUEST  int16
	SET_GENDER            int16
	AFTER_LOGIN           int16
	REGISTER_PIN          int16
	SERVERLIST_REQUEST    int16
	TO_WORLDLIST          int16
	VIEW_ALL_CHAR_REQUEST int16
	VIEW_ALL_CHAR_CONNECT int16
	VIEW_ALL_CHAR         int16
	CHAR_SELECT           int16
	CHECK_CHAR_NAME       int16
	CREATE_CHAR           int16
	ERROR_LOG             int16
	RELOG                 int16
	// CHANNEL
	PLAYER_LOGGEDIN        int16
	CHANGE_MAP             int16
	CHANGE_CHANNEL         int16
	ENTER_CASH_SHOP        int16
	MOVE_PLAYER            int16
	CANCEL_CHAIR           int16
	USE_CHAIR              int16
	CLOSE_RANGE_ATTACK     int16
	RANGED_ATTACK          int16
	MAGIC_ATTACK           int16
	PASSIVE_ENERGY         int16
	ENERGY_CHARGE_ATTACK   int16
	TAKE_DAMAGE            int16
	GENERAL_CHAT           int16
	CLOSE_CHALKBOARD       int16
	FACE_EXPRESSION        int16
	USE_ITEMEFFECT         int16
	NPC_TALK               int16
	NPC_TALK_MORE          int16
	NPC_SHOP               int16
	STORAGE                int16
	HIRED_MERCHANT_REQUEST int16
	DUEY_ACTION            int16
	ITEM_SORT              int16
	ITEM_MOVE              int16
	USE_ITEM               int16
	CANCEL_ITEM_EFFECT     int16
	USE_FISHING_ITEM       int16
	USE_SUMMON_BAG         int16
	PET_FOOD               int16
	USE_MOUNT_FOOD         int16
	USE_CASH_ITEM          int16
	USE_CATCH_ITEM         int16
	USE_SKILL_BOOK         int16
	USE_RETURN_SCROLL      int16
	MAKER_SKILL            int16
	USE_UPGRADE_SCROLL     int16
	DISTRIBUTE_AP          int16
	DISTRIBUTE_AUTO_AP     int16
	HEAL_OVER_TIME         int16
	DISTRIBUTE_SP          int16
	SPECIAL_MOVE           int16
	CANCEL_BUFF            int16
	SKILL_EFFECT           int16
	MESO_DROP              int16
	GIVE_FAME              int16
	CHAR_INFO_REQUEST      int16
	MOB_DAMAGED            int16
	SPAWN_PET              int16
	CANCEL_DEBUFF          int16
	CHANGE_MAP_SPECIAL     int16
	USE_INNER_PORTAL       int16
	TROCK_ADD_MAP          int16
	QUEST_ACTION           int16
	EFFECT_ON_OFF          int16
	THROW_BOMB             int16
	SKILL_MACRO            int16
	REPORT_PLAYER          int16
	TREASUER_CHEST         int16 `properties:"TREASUER_CHEST,default=65535"`
	MULTI_CHAT             int16
	WHISPER                int16
	SPOUSE_CHAT            int16
	MESSENGER              int16
	PLAYER_INTERACTION     int16
	PARTY_OPERATION        int16
	DENY_PARTY_REQUEST     int16
	GUILD_OPERATION        int16
	DENY_GUILD_REQUEST     int16
	BUDDYLIST_MODIFY       int16
	NOTE_ACTION            int16
	USE_DOOR               int16
	CHANGE_KEYMAP          int16
	RING_ACTION            int16
	OPEN_FAMILY            int16
	ADD_FAMILY             int16
	ACCEPT_FAMILY          int16
	USE_FAMILY             int16
	ALLIANCE_OPERATION     int16
	BBS_OPERATION          int16
	ENTER_MTS              int16
	SOLOMON                int16
	MOVE_PET               int16
	PET_CHAT               int16
	PET_COMMAND            int16
	PET_LOOT               int16
	PET_AUTO_POT           int16
	MOVE_SUMMON            int16
	SUMMON_ATTACK          int16
	DAMAGE_SUMMON          int16
	MOVE_LIFE              int16
	AUTO_AGGRO             int16
	MOB_DAMAGE_MOB         int16
	MONSTER_BOMB           int16
	NPC_ACTION             int16
	ITEM_PICKUP            int16
	HYPNOTIZE              int16
	DAMAGE_REACTOR         int16
	TOUCH_REACTOR          int16
	MONSTER_CARNIVAL       int16
	OBJECT_REQUEST         int16
	PARTY_SEARCH_REGISTER  int16
	PARTY_SEARCH_START     int16
	PLAYER_UPDATE          int16
	TOUCHING_CS            int16
	CASH_SHOP              int16
	COUPON_CODE            int16
	MAPLETV                int16
	MTS_OP                 int16
	SCRIPTED_ITEM          int16
	REVIVE_ITEM            int16
	SUMMON_TALK            int16
	MONSTER_BOOK_COVER     int16
	VICIOUS_HAMMER         int16
	ChatRoom_SYSTEM        int16
}
